TrainingArguments:
  num_train_epochs: 5
  warmup_steps: 500
  per_device_train_batch_size: 8
  weight_decay: 0.01
  logging_steps: 1
  evaluation_strategy: steps
  eval_steps: 1
  save_steps: 2
  gradient_accumulation_steps: 2
