artifacts_root: outputs

data_ingestion:
  root_dir: outputs/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: outputs/data_ingestion/data.zip
  unzip_dir: outputs/data_ingestion


data_validation:
  root_dir: outputs/data_validation
  STATUS_FILE: outputs/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]


data_transformation:
  root_dir: outputs/data_transformation
  data_path: outputs/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: outputs/model_trainer
  data_path: outputs/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail


model_evaluation:
  root_dir: outputs/model_evaluation
  data_path: outputs/data_transformation/samsum_dataset
  model_path: outputs/model_trainer/pegasus-samsum-model
  tokenizer_path: outputs/model_trainer/tokenizer
  metric_file_name: outputs/model_evaluation/metrics.csv
